/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class agent */

#ifndef _Included_agent
#define _Included_agent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     agent
 * Method:    C_getLocalTime
 * Signature: (LBEACON;)LBEACON;
 */
JNIEXPORT jobject JNICALL Java_agent_C_1getLocalTime
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
